### ISSUE TITLE
Storage account name length exceeds the maximum length allowed

### ISSUE THREAD

**Issue by garg-amit** [Azure-Samples/azure-ml-federated-learning#129]
**Describe the bug**
- Encountered the below issue when I executed the provisioning script.

`The provided deployment name 'fl2-1-3268639957-deploy-internal-endpoint-1-francecentral-storage' has a length of '65' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.`

We might need to handle the SA's name length in the provisioning script itself (maybe shorten the suffix `-deploy-internal-endpoint-1-francecentral-storage` ).

**Comment by jfomhover** [comment]
This has been resolved in #132
