### ISSUE TITLE
Point to "latest" environment in reference examples

### ISSUE THREAD

**Issue by dkmiller** [Azure-Samples/azure-ml-federated-learning#13]
From the internal Teams thread,

> [Latest not supported for curated environments](https://teams.microsoft.com/l/message/19:1bd3482127dd4330984bfa1029aaf38b@thread.tacv2/1644365500037?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=13e1702e-ccb0-4b25-aff8-d637a92c658b&parentMessageId=1644365500037&teamName=Azure%20ML%20vNext&channelName=Environments&createdTime=1644365500037)

this is now supported, see e.g. [hello-mlflow.yml](https://github.com/Azure/azureml-examples/blob/main/cli/jobs/basics/hello-mlflow.yml#L4)

**Comment by garg-amit** [comment]
All the curated environments have the "latest" tag so no changes are required. cc @thomasp-ms
