### ISSUE TITLE
Invalid template deployment error

### ISSUE THREAD

**Issue by garg-amit** [Azure-Samples/azure-ml-federated-learning#130]
**Describe the bug**

- Got the following error when I try to execute the provisioning script with the same demo name but after deleting the prev. resource group (even in different subscriptions) - Not sure if this is expected.

`{"code": "InvalidTemplateDeployment", "message": "The template deployment 'open_sandbox_setup' is not valid according to the validation procedure. The tracking id is 'f6e64397-6b33-4990-a7b3-48b4ba92c4c8'. See inner errors for details."}
Inner Errors:
{"code": "PreflightValidationCheckFailed", "message": "Preflight validation failed. Please refer to the details for the specific errors."}
Inner Errors:
{"code": "StorageAccountAlreadyTaken", "target": "stamlfldemofghjk4", "message": "The storage account named stamlfldemofghjk4 is already taken."}`

**Comment by jfomhover** [comment]
I think this happens because of the truncation of the storage name. I'll take it.

**Comment by jfomhover** [comment]
I think that might have happened because the provisioned started, and then you re-initiated a build, but it uses the previous demoBaseName? I'd love to have a clean repro with a recent build, considering how many changes happened in the provisioning.

**Comment by jfomhover** [comment]
and if you don't see any repro, then let's mark as closed? @garg-amit

**Comment by garg-amit** [comment]
@jfomhover Tried to repro but got the following error 

`{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At 
least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ConflictError\\\",\\r\\n    \\\"message\\\": \\\"A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}`

**Comment by jfomhover** [comment]
I think this happens because keyvaults are not fully deleted when you delete them but are "soft deleted" to allow you to recover from it. Maybe I can add a node on this in the installation, some troubleshooting section.

**Comment by jfomhover** [comment]
I've filed an issue for next release to create a troubleshooting page #159

**Comment by jfomhover** [comment]
Explained in the TSG now :)
