### ISSUE TITLE
Learning about recourse provision + update auto provision script

### ISSUE THREAD

**Issue by jialei777** [Azure-Samples/azure-ml-federated-learning#14]

**Comment by jialei777** [comment]
Add `--overwrite` when labeling the node:
```
kubectl label nodes $kubenodes_name training_node=my_beefy_node
```

**Comment by jialei777** [comment]
In `ConnectSiloToOrchestrator.ps1` script, set `installNvidiaDevicePlugin=True`. 

```
az k8s-extension create --name arcml-extension --extension-type Microsoft.AzureML.Kubernetes --config enableTraining=True installNvidiaDevicePlugin=True --cluster-type connectedClusters --cluster-name $ArcClusterName --resource-group $ArcClusterRGName --scope cluster --auto-upgrade-minor-version False
```

**Comment by thomasp-ms** [comment]
@jialei777 this change looks pretty straightforward but if you need help with anything, do not hesitate to pull me in - I'm the one who originally wrote these scripts

**Comment by jialei777** [comment]
@thomasp-ms Thanks for offering the help. There are more learning on the way. So I am thinking about documenting things here and updating the script later.

**Comment by talbaumel** [comment]
@jialei777 I think we should change the default instance type `"Standard_A2_v2"` and add instruction to how to add the "beefy cluster" to the pool. It seems to work so far 👍
