### ISSUE TITLE
Inaccessible keyvault

### ISSUE THREAD

**Issue by majercakdavid** [Azure-Samples/azure-ml-federated-learning#189]
**Describe the bug**
When creating open sandbox owner does not have access to the keyvault

**Expected behavior**

- Owner/User has ability to do CRUD operation on contents of the keyvault

**Steps to fix**

- Add access policy that allows to perform CRUD operation over the default keyvault in the bicep template

**Comment by majercakdavid** [comment]
This is essentially blocked by: https://stackoverflow.com/questions/73150997/roleassignment-with-current-user-id

**Comment by jfomhover** [comment]
There's no way to provision the keyvault so that the current user has access to it. We'll have to rely on users setting up access for themselves.

Notes to implement in our tutorials, instead of using the UI, use az cli?

```bash
# to show current user object id
az ad signed-in-user show

# to set policy for ths user
az keyvault set-policy -n MyVault --secret-permissions list set delete --object-id {GUID}
```
