### ISSUE TITLE
Fix/update some outdated docs/links

### ISSUE THREAD

**Issue by ShizeSu06** [Azure-Samples/azure-ml-federated-learning#21]
I noticed that some of the materials in this repo are a bit outdated. For example, in [this file](https://github.com/Azure-Samples/azure-ml-federated-learning/blob/main/automated_provisioning/sample_job/job.yml), "latest" tag for docker env version is now available, but the doc is still using the fixed (and outdated) version "24", which could cause docker image vulnerabilities issue. Also, the shared example fl experiment link in [this page](https://github.com/Azure-Samples/azure-ml-federated-learning/tree/main/fl_arc_k8s) is pointing to an old fl experiment which is using a very ugly visualization and looks complicated.

Creating this issue about updating these outdated materials.

**Comment by thomasp-ms** [comment]
Update shrike version to the most recent one too. For exp link, use the new one I'll have created.

For data, any dataset can be used:
- irisdata is supposed to mimick model weights, or some public data used to pre-train the model in the orchestrator: rename
- the other datasets are the silo data: rename first, split the second and rename

Aggregation subgraph:
- turn that into a real triple input graph (as opposed to 2 and then 2)
