### ISSUE TITLE
App insight Deployment error during FL demo

### ISSUE THREAD

**Issue by luigiw** [Azure-Samples/azure-ml-federated-learning#242]
**Describe the bug**

FL demo deployment causes an app insight deployment error.

**To Reproduce**
1. Go to  https://github.com/Azure-Samples/azure-ml-federated-learning/blob/main/docs/quickstart.md
2. Click on the first "Deploy to Azure" button
3. Fill in the form and I used westus3 as the region.
4. See error below for the App insight 

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Region doesn't support Classic resource mode for Application Insights resources. Please use Workspace-based mode."
    }
}

**Expected behavior**

The FL demo deployment to go through.

**Screenshots**

**Additional context**

**Comment by jfomhover** [comment]
Sounds like the reason is that we're using "classic" appinsights instead of workspace appinsights. We need to modify our bicep provisioning to align with the latest provisioning strategy for appinsights instances attached to our demo workspace.

**Comment by jfomhover** [comment]
Provisioning of app insights has been removed from our bicep files in release-06.

**Comment by jfomhover** [comment]
We had to rollback the changes. We initially removed appinsights from the workspace provisioning, but that's not supported in 3p subscriptions. We've restored the changes and we'll have to figure out how to provision workspace-based appinsights in a coming release.

related: #294
