### ISSUE TITLE
DP for pneumonia has issue of "tensors not on the same device"

### ISSUE THREAD

**Issue by ww-aims** [Azure-Samples/azure-ml-federated-learning#273]
**Describe the bug**

- When DP is turned on for pneumonia example, the job reports error that "tensors are not on the same device" after several epochs of training: https://ml.azure.com/experiments/id/519951ec-9756-4179-ad2a-db1438f32ec6/runs/purple_ring_25jp79yqrm?wsid=/subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourcegroups/wen_babel_fl/workspaces/aml-fl-benchmarks-gpu5&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#  or even after an iteration is done: https://ml.azure.com/experiments/id/519951ec-9756-4179-ad2a-db1438f32ec6/runs/teal_roof_2gb0qnvfds?wsid=/subscriptions/48bbc269-ce89-4f6f-9a12-c6f91fcb772d/resourceGroups/wen_babel_fl/providers/Microsoft.MachineLearningServices/workspaces/aml-fl-benchmarks-gpu5&tid=72f988bf-86f1-41af-91ab-2d7cd011db47#

- I checked the data and model, which should be both on the same device. I only added some code for benchmarking purpose and should not affect the model. For more detail, please refer to the "code" tab in the portal.

- Additionally, I also tested the behavior when DDP is disabled by running on 1gpu, however the issue still seems to persist.

- For ccfraud example, DP works well and there is no such issue

**Screenshots**
![image](https://user-images.githubusercontent.com/120244188/220444539-3420c7ee-ee02-4185-85ab-884e7cb49016.png)

**Comment by garg-amit** [comment]
I was unable to repro this error, so I am closing it for now, assuming that it has been resolved with the latest version of torch/torchvision. If this issue occurs again, feel free to reopen it.
