### ISSUE TITLE
Clean-up dependencies

### ISSUE THREAD

**Issue by jfomhover** [Azure-Samples/azure-ml-federated-learning#29]
IMPORTANT: to apply in the `release-sdkv2-mvp` branch

After we merge the initial dpv2 basic pipeline #27 :
- [ ] remove pipelines/config/
- [ ] remove pipelines/experiments/
- [ ] remove tes-api-on-azure-ml/
- [ ] clean up `requirements.txt` files that are floating around, and leave only the root `requirements.txt` file

**Comment by thomasp-ms** [comment]
re-opening because I forgot to clean up the requirements files
