### ISSUE TITLE
AttributeError: module 'torch' has no attribute '_six'

### ISSUE THREAD

**Issue by garg-amit** [Azure-Samples/azure-ml-federated-learning#319]
**Describe the bug**
I've recently started experiencing the following issue in the MNIST and the Pneumonia example: `AttributeError: module 'torch' has no attribute '_six'`. 

**To Reproduce**
1. Submit either MNIST or PNEUMONIA example
2. Look at the silo's training logs.

**Expected behavior**
It should run seamlessly. 

**Screenshot**
<img width="563" alt="image" src="https://user-images.githubusercontent.com/19791871/228593599-93baf038-85e2-4e3b-abad-6c0ba0e340bd.png">

**Comment by Peter-PengH** [comment]
i have the same  issue

**Comment by jfomhover** [comment]
This looks like a problem related to a pytorch version? Does that show systematically in our CI/CD tests?

**Comment by jfomhover** [comment]
Ok I was able ot repro as well.

Looks like this import should not happen (depending on torch vs torchvision versions?)

There was a PR to fix this line:
https://github.com/pytorch/vision/pull/7243

Maybe we can just figure out the right combination of torch/torchvision versions? I'm curious why this did not fail our integration tests though.

**Comment by jfomhover** [comment]
probably safer by using

  - pytorch=1.12.1
  - torchvision=0.13.1

(if we don't need pytorch 1.13)

**Comment by garg-amit** [comment]
I updated both pipelines with the latest version of pytorch i.e. 2.0.0 and torchvision i.e. 0.15.1. This resolved the issue.
