### ISSUE TITLE
Pain point: allow for aggregated models to be stored into a single folder on datastore

### ISSUE THREAD

**Issue by jfomhover** [Azure-Samples/azure-ml-federated-learning#39]
Users would love to see a better naming scheme for the aggregation output folders, because it is hard to navigate.

"I would to be able to navigate using azure storage explorer with more meaningful names something like <experiment-name>_<run_date/number>_<round_number>".

We could address this in our MVP by changing the custom path used for the output of the aggregation component.

**Comment by thomasp-ms** [comment]
This will be done in iteration, removing from this milestone

**Comment by garg-amit** [comment]
#55
