### ISSUE TITLE
Deduplicate code in mlops directory

### ISSUE THREAD

**Issue by thomasp-ms** [Azure-Samples/azure-ml-federated-learning#40]
The `mlops/internal_silos` and `mlops/external_silos` folders will have some duplicated code and files. Once these folders are stable, refactor into:
- `mlops/internal_silos`
- `mlops/external_silos`
- `mlops/shared`

where the last folder contains all the shared resources.

This is NOT absolutely required for the August release (SDKv2 MVP)

**Comment by jfomhover** [comment]
Once we merge #58 , I propose we wipe our the `mlops/` subfolder and rewrite external silos provisioning in bicep?
