### ISSUE TITLE
Define and implement how we provision the datasets in the vanilla demo setup

### ISSUE THREAD

**Issue by jfomhover** [Azure-Samples/azure-ml-federated-learning#60]
The pull request merging the native bicep provisioning script #58 is raising the question of how to quickly and effortlessly (for the users) provision the datasets in each silo in order to run a relevant demo.

The PR took the option to just use direct URLs inside the config yaml of our submission script to avoid this step, but we need to:
- [x] define how we'd want the users of our repo to upload (or not) the example data into their bicep provisioned silos
- [x] implement those steps in our tutorial/doics
- [x] align the config yaml with this definition

**Comment by garg-amit** [comment]
As discussed, removing this from iteration-02
