### ISSUE TITLE
Guide + pitfalls on refactoring your existing ML code to be FL-ready

### ISSUE THREAD

**Issue by dkmiller** [Azure-Samples/azure-ml-federated-learning#7]
From an internal re-write of some Cognitive Services training code to leverage the Shrike federated pipeline API, there are a lot of lessons we should have learned.

Put those in a easy-to-follow guide on:

- What do you need to do to turn "training script" into "federated pipeline"
- Common pitfalls and things to watch out for
- Best practices (e.g., log metrics to "parent" pipeline)

**Comment by jfomhover** [comment]
This has been implemented in #256
