### ISSUE TITLE
Getting deployment already exists error

### ISSUE THREAD

**Issue by garg-amit** [Azure-Samples/azure-ml-federated-learning#77]
> I'm getting the following error when using the bicep script to provision resources:

`{"code": "InvalidDeploymentLocation", "message": "Invalid deployment location 'westus'. The deployment '54475218-5cae-57f7-9f9f-514a4701c1b4' already exists in location 'eastus'."}`

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Any log messages given by the failure
>
![image](https://user-images.githubusercontent.com/19791871/192038050-320bfb9a-c5ea-47c4-8aed-47a801aaa891.png)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by thomasp-ms** [comment]
We noticed today that the issue occurs only if the location of the base RG (the one created as a first step before deploying the Bicep template) is the same as one of the 3 silos locations but different from the one where a successful deployment happened before

**Comment by thomasp-ms** [comment]
[Here](https://ms.portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F48bbc269-ce89-4f6f-9a12-c6f91fcb772d%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2F54475218-5cae-57f7-9f9f-514a4701c1b4) is the deployment that already exists. It is about the custom role indeed. I'm going to try a quick fix by adding one more argument to the guid-generating function.

FYI @garg-amit @jfomhover
