### ISSUE TITLE
Use Mermaid to render federated pipeline architecture

### ISSUE THREAD

**Issue by dkmiller** [Azure-Samples/azure-ml-federated-learning#9]
Imitate this: https://github.com/Azure/shrike/pull/357 .

@ShizeSu06 + @thomasp-ms &mdash; not urgent, but worth thinking about.

**Comment by jfomhover** [comment]
Closing this old issue for now, we have so few schemas that this would not bring too much value. Also, we can reconsider once we know where the official FL native support documentation will be hosted.
